// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	orm "github.com/rakhmadbudiono/code-scanner/internal/orm"
	mock "github.com/stretchr/testify/mock"
)

// IController is an autogenerated mock type for the IController type
type IController struct {
	mock.Mock
}

// CreateRepository provides a mock function with given fields: repo
func (_m *IController) CreateRepository(repo *orm.Repository) (*orm.Repository, error) {
	ret := _m.Called(repo)

	var r0 *orm.Repository
	if rf, ok := ret.Get(0).(func(*orm.Repository) *orm.Repository); ok {
		r0 = rf(repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orm.Repository)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*orm.Repository) error); ok {
		r1 = rf(repo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteRepository provides a mock function with given fields: ID
func (_m *IController) DeleteRepository(ID string) error {
	ret := _m.Called(ID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllRepositories provides a mock function with given fields:
func (_m *IController) GetAllRepositories() ([]orm.Repository, error) {
	ret := _m.Called()

	var r0 []orm.Repository
	if rf, ok := ret.Get(0).(func() []orm.Repository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]orm.Repository)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllResultsByRepositoryID provides a mock function with given fields: ID
func (_m *IController) GetAllResultsByRepositoryID(ID string) ([]orm.Result, error) {
	ret := _m.Called(ID)

	var r0 []orm.Result
	if rf, ok := ret.Get(0).(func(string) []orm.Result); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]orm.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRepositoryByID provides a mock function with given fields: ID
func (_m *IController) GetRepositoryByID(ID string) (*orm.Repository, error) {
	ret := _m.Called(ID)

	var r0 *orm.Repository
	if rf, ok := ret.Get(0).(func(string) *orm.Repository); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orm.Repository)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScanRepository provides a mock function with given fields: ID
func (_m *IController) ScanRepository(ID string) error {
	ret := _m.Called(ID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRepository provides a mock function with given fields: repo
func (_m *IController) UpdateRepository(repo *orm.Repository) (*orm.Repository, error) {
	ret := _m.Called(repo)

	var r0 *orm.Repository
	if rf, ok := ret.Get(0).(func(*orm.Repository) *orm.Repository); ok {
		r0 = rf(repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orm.Repository)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*orm.Repository) error); ok {
		r1 = rf(repo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIController interface {
	mock.TestingT
	Cleanup(func())
}

// NewIController creates a new instance of IController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIController(t mockConstructorTestingTNewIController) *IController {
	mock := &IController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
