// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IScanProcessor is an autogenerated mock type for the IScanProcessor type
type IScanProcessor struct {
	mock.Mock
}

// Process provides a mock function with given fields: repoLink
func (_m *IScanProcessor) Process(repoLink string) error {
	ret := _m.Called(repoLink)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(repoLink)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIScanProcessor interface {
	mock.TestingT
	Cleanup(func())
}

// NewIScanProcessor creates a new instance of IScanProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIScanProcessor(t mockConstructorTestingTNewIScanProcessor) *IScanProcessor {
	mock := &IScanProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
